
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"


providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"