http:
  routers:
    api-router:
      rule: 'Host(`{{ env "APP_DOMAIN" }}`) && PathPrefix(`/api/v1`)'
      service: api-service
      entryPoints:
        - websecure
      priority: 100
      middlewares:
        - cors-middleware@file
      tls:
        certResolver: letsencrypt

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http:/api:9000"