http:
  routers:
    admin-router:
      rule: 'Host(`{{ env "APP_DOMAIN" }}`) && PathPrefix(`/`)'
      service: web
      entryPoints:
        - websecure
      priority: 100
      middlewares:
        - cors-middleware@file
      tls:
        certResolver: letsencrypt


  services:
    web:
      loadBalancer:
        servers:
          - url: "http://web:9001"